In [1]:
import tensorflow as tf

# Membuat tensor dengan nilai random

In [2]:
random_tensor = tf.random.uniform([5,5],maxval=5,dtype=tf.int64)
random_tensor

<tf.Tensor: shape=(5, 5), dtype=int64, numpy=
array([[3, 0, 2, 4, 3],
       [0, 1, 0, 4, 0],
       [4, 1, 4, 4, 4],
       [2, 3, 0, 3, 4],
       [4, 1, 3, 4, 0]], dtype=int64)>

# Membuat tensor dari sebuah list dengan nilai bilangan prima

In [3]:
prime_tensor = tf.constant([2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97], shape= (5,5), dtype=tf.int64 )
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=int64, numpy=
array([[ 2,  3,  5,  7, 11],
       [13, 17, 19, 23, 29],
       [31, 37, 41, 43, 47],
       [53, 59, 61, 67, 71],
       [73, 79, 83, 89, 97]], dtype=int64)>

# Dimensi random_tensor

In [4]:
random_tensor.shape

TensorShape([5, 5])

# Dimensi prime_tensor

In [5]:
prime_tensor.shape

TensorShape([5, 5])

# Aritmatika 

In [7]:
#Penjumlahan
print("Hasil Penjumlahan Variable random_tensor dan prime_tensor adalah:")
print(tf.add(random_tensor, prime_tensor))
print("---------------------------------------------------------------")

#Pengurangan
print("Hasil Pengurangan Variable random_tensor dan prime_tensor adalah:")
print(tf.substract(random_tensor, prime_tensor))
print("---------------------------------------------------------------")


Hasil Penjumlah Variable random_tensor dan prime_tensor adalah:
tf.Tensor(
[[ 5  3  7 11 14]
 [13 18 19 27 29]
 [35 38 45 47 51]
 [55 62 61 70 75]
 [77 80 86 93 97]], shape=(5, 5), dtype=int64)


In [8]:
#Perkalian
print("Hasil Perkalian Variable random_tensor dan prime_tensor adalah:")
print(tf.multiply(random_tensor, prime_tensor))
print("---------------------------------------------------------------")

#Pembagian
print("Hasil Pembagian Variable random_tensor dan prime_tensor adalah:")
print(tf.divide(random_tensor, prime_tensor))
print("---------------------------------------------------------------")


Hasil Perkalian Variable random_tensor dan prime_tensor adalah:
tf.Tensor(
[[  6   0  10  28  33]
 [  0  17   0  92   0]
 [124  37 164 172 188]
 [106 177   0 201 284]
 [292  79 249 356   0]], shape=(5, 5), dtype=int64)
---------------------------------------------------------------
Hasil Pembagian Variable random_tensor dan prime_tensor adalah:
tf.Tensor(
[[1.5        0.         0.4        0.57142857 0.27272727]
 [0.         0.05882353 0.         0.17391304 0.        ]
 [0.12903226 0.02702703 0.09756098 0.09302326 0.08510638]
 [0.03773585 0.05084746 0.         0.04477612 0.05633803]
 [0.05479452 0.01265823 0.03614458 0.04494382 0.        ]], shape=(5, 5), dtype=float64)
---------------------------------------------------------------


In [9]:
#Perpangkatan
print("Hasil Perpangkatan Variable random_tensor dan prime_tensor adalah:")
print(tf.pow(random_tensor, prime_tensor))
print("---------------------------------------------------------------")

Hasil Perpangkatan Variable random_tensor dan prime_tensor adalah:
tf.Tensor(
[[                   9                    0                   32
                 16384               177147]
 [                   0                    1                    0
        70368744177664                    0]
 [ 4611686018427387904                    1                    0
                     0                    0]
 [    9007199254740992 -1178661806862719173                    0
  -4014347941998366949                    0]
 [                   0                    1  7833852915060663003
                     0                    0]], shape=(5, 5), dtype=int64)
---------------------------------------------------------------


## Nilai Maksimal dan Minimal dari Variable random_tensor

### 1. Nilai Maksimum

In [12]:
nilai_max_1 = tf.argmax(random_tensor, axis=0)
nilai_max_2 = tf.argmax(random_tensor, axis=1)
print("Nilai Maksimum berdasarkan kolom: ", nilai_max_1)
print("Nilai Maksimum berdasarkan baris: ", nilai_max_2)

Nilai Maksimum berdasarkan kolom:  tf.Tensor([2 3 2 0 2], shape=(5,), dtype=int64)
Nilai Maksimum berdasarkan baris:  tf.Tensor([3 3 0 4 0], shape=(5,), dtype=int64)


### 2. Nilai Minimum

In [11]:
nilai_min_1 = tf.argmin(random_tensor, axis=0)
nilai_min_2 = tf.argmin(random_tensor, axis=1)
print("Nilai Minimum berdasarkan kolom: ", nilai_min_1)
print("Nilai Minimum berdasarkan baris: ", nilai_min_2)

Nilai Minimum berdasarkan kolom:  tf.Tensor([1 0 1 3 1], shape=(5,), dtype=int64)
Nilai Minimum berdasarkan baris:  tf.Tensor([1 0 1 2 4], shape=(5,), dtype=int64)


# Concatenation

In [13]:
#Menggunakan metode tf.concat()
concat_variable = tf.concat([random_tensor,prime_tensor], axis = 0)
print(f"Size data yang sudah di-concat {concat_variable.shape}")
print(concat_variable)

Size data yang sudah di-concat (10, 5)
tf.Tensor(
[[ 3  0  2  4  3]
 [ 0  1  0  4  0]
 [ 4  1  4  4  4]
 [ 2  3  0  3  4]
 [ 4  1  3  4  0]
 [ 2  3  5  7 11]
 [13 17 19 23 29]
 [31 37 41 43 47]
 [53 59 61 67 71]
 [73 79 83 89 97]], shape=(10, 5), dtype=int64)


# Sorting Variable secara Descending

### random_tensor

In [14]:
print("Nilai Variable Setelah di sorting secara Descending:")
tf.sort(random_tensor, direction="DESCENDING")

Nilai Variable Setelah di sorting secara Descending:


<tf.Tensor: shape=(5, 5), dtype=int64, numpy=
array([[4, 3, 3, 2, 0],
       [4, 1, 0, 0, 0],
       [4, 4, 4, 4, 1],
       [4, 3, 3, 2, 0],
       [4, 4, 3, 1, 0]], dtype=int64)>

### prime_tensor

In [15]:
print("Nilai Variable Setelah di sorting secara Descending:")
tf.sort(prime_tensor, direction="DESCENDING")

Nilai Variable Setelah di sorting secara Descending:


<tf.Tensor: shape=(5, 5), dtype=int64, numpy=
array([[11,  7,  5,  3,  2],
       [29, 23, 19, 17, 13],
       [47, 43, 41, 37, 31],
       [71, 67, 61, 59, 53],
       [97, 89, 83, 79, 73]], dtype=int64)>